const Employee = require('../models/Employee');
const path = require('path');
const fs = require('fs');

// Get all employees with filtering, search, and pagination
exports.getEmployees = async (req, res) => {
  try {
    if (!req.college || !req.college._id) {
      return res.status(401).json({ message: 'College information not found' });
    }

    const collegeId = req.college._id;
    
    // Filtering, searching, and sorting
    const { page = 1, limit = 10, role, department, status, search, sortBy = 'createdAt', order = 'desc' } = req.query;

    // Build query filters
    let query = { collegeId };

    if (role && role !== 'All Roles' && role !== '') {
      query.role = role;
    }
    if (department && department !== 'All Departments' && department !== '') {
      query.department = department;
    }
    if (status && status !== 'All Status' && status !== '') {
      query.status = status;
    }

    // Search by name or empId or mobile
    if (search && search !== '') {
      query.$or = [
        { name: { $regex: search, $options: 'i' } },
        { empId: { $regex: search, $options: 'i' } },
        { mobile: { $regex: search, $options: 'i' } },
        { email: { $regex: search, $options: 'i' } }
      ];
    }

    // Calculate pagination
    const skip = (parseInt(page) - 1) * parseInt(limit);

    // Build sort object
    const sortObj = {};
    sortObj[sortBy] = order === 'desc' ? -1 : 1;

    // Fetch data
    const employees = await Employee.find(query)
      .sort(sortObj)
      .skip(skip)
      .limit(parseInt(limit))
      .select('-__v');

    // Get total count for pagination
    const total = await Employee.countDocuments(query);

    res.status(200).json({
      message: 'Employees fetched successfully',
      data: employees,
      total,
      page: parseInt(page),
      limit: parseInt(limit),
      pages: Math.ceil(total / parseInt(limit))
    });
  } catch (error) {
    console.error('Get Employees Error:', error);
    res.status(500).json({ message: 'Error fetching employees', error: error.message });
  }
};

// Get single employee by ID
exports.getEmployeeById = async (req, res) => {
  try {
    if (!req.college || !req.college._id) {
      return res.status(401).json({ message: 'College information not found' });
    }

    const collegeId = req.college._id;
    const employeeId = req.params.id;

    const employee = await Employee.findOne({ _id: employeeId, collegeId }).select('-__v');

    if (!employee) {
      return res.status(404).json({ message: 'Employee not found' });
    }

    res.status(200).json({
      message: 'Employee fetched successfully',
      data: employee
    });
  } catch (error) {
    console.error('Get Employee By ID Error:', error);
    res.status(500).json({ message: 'Error fetching employee', error: error.message });
  }
};

// Create new employee
exports.createEmployee = async (req, res) => {
  try {
    if (!req.college || !req.college._id) {
      return res.status(401).json({ message: 'College information not found' });
    }

    const collegeId = req.college._id;
    const { name, email, mobile, role, department, dateOfJoining, dateOfBirth, gender, address, status } = req.body;

    // Validation
    if (!name || !email || !mobile || !role || !department) {
      return res.status(400).json({ message: 'Missing required fields' });
    }

    // Check if email already exists
    const existingEmployee = await Employee.findOne({ email, collegeId });
    if (existingEmployee) {
      return res.status(400).json({ message: 'Email already exists for this college' });
    }

    // Handle profile photo
    let profilePhoto = '';
    if (req.file) {
      profilePhoto = `/uploads/${req.file.filename}`;
    }

    // Create employee (empId will be auto-generated by pre-save hook)
    const newEmployee = new Employee({
      name,
      email,
      mobile,
      role,
      department,
      dateOfJoining,
      dateOfBirth,
      gender,
      address,
      status: status || 'Active',
      profilePhoto,
      collegeId
    });

    await newEmployee.save();

    res.status(201).json({
      message: 'Employee created successfully',
      data: newEmployee
    });
  } catch (error) {
    console.error('Create Employee Error:', error);
    res.status(500).json({ message: 'Error creating employee', error: error.message });
  }
};

// Update employee
exports.updateEmployee = async (req, res) => {
  try {
    if (!req.college || !req.college._id) {
      return res.status(401).json({ message: 'College information not found' });
    }

    const collegeId = req.college._id;
    const employeeId = req.params.id;
    const { name, email, mobile, role, department, dateOfJoining, dateOfBirth, gender, address, status } = req.body;

    // Check if employee exists
    const employee = await Employee.findOne({ _id: employeeId, collegeId });
    if (!employee) {
      return res.status(404).json({ message: 'Employee not found' });
    }

    // Check if email is being changed and if it already exists
    if (email && email !== employee.email) {
      const existingEmployee = await Employee.findOne({ email, collegeId });
      if (existingEmployee) {
        return res.status(400).json({ message: 'Email already exists for this college' });
      }
    }

    // Update fields
    if (name) employee.name = name;
    if (email) employee.email = email;
    if (mobile) employee.mobile = mobile;
    if (role) employee.role = role;
    if (department) employee.department = department;
    if (dateOfJoining) employee.dateOfJoining = dateOfJoining;
    if (dateOfBirth) employee.dateOfBirth = dateOfBirth;
    if (gender) employee.gender = gender;
    if (address !== undefined) employee.address = address;
    if (status) employee.status = status;

    // Handle profile photo
    if (req.file) {
      // Remove old photo if exists
      if (employee.profilePhoto) {
        const oldPhotoPath = path.join(__dirname, '..', employee.profilePhoto);
        if (fs.existsSync(oldPhotoPath)) {
          fs.unlinkSync(oldPhotoPath);
        }
      }
      employee.profilePhoto = `/uploads/${req.file.filename}`;
    }

    await employee.save();

    res.status(200).json({
      message: 'Employee updated successfully',
      data: employee
    });
  } catch (error) {
    console.error('Update Employee Error:', error);
    res.status(500).json({ message: 'Error updating employee', error: error.message });
  }
};

// Delete employee
exports.deleteEmployee = async (req, res) => {
  try {
    if (!req.college || !req.college._id) {
      return res.status(401).json({ message: 'College information not found' });
    }

    const collegeId = req.college._id;
    const employeeId = req.params.id;

    const employee = await Employee.findOneAndDelete({ _id: employeeId, collegeId });

    if (!employee) {
      return res.status(404).json({ message: 'Employee not found' });
    }

    // Remove profile photo if exists
    if (employee.profilePhoto) {
      const photoPath = path.join(__dirname, '..', employee.profilePhoto);
      if (fs.existsSync(photoPath)) {
        fs.unlinkSync(photoPath);
      }
    }

    res.status(200).json({
      message: 'Employee deleted successfully',
      data: employee
    });
  } catch (error) {
    console.error('Delete Employee Error:', error);
    res.status(500).json({ message: 'Error deleting employee', error: error.message });
  }
};

// Get unique roles for filter
exports.getRoles = async (req, res) => {
  try {
    if (!req.college || !req.college._id) {
      return res.status(401).json({ message: 'College information not found' });
    }

    const collegeId = req.college._id;
    const roles = await Employee.distinct('role', { collegeId });
    
    res.status(200).json({
      message: 'Roles fetched successfully',
      data: roles || []
    });
  } catch (error) {
    console.error('Get Roles Error:', error);
    res.status(500).json({ message: 'Error fetching roles', error: error.message });
  }
};

// Get unique departments for filter
exports.getDepartments = async (req, res) => {
  try {
    if (!req.college || !req.college._id) {
      return res.status(401).json({ message: 'College information not found' });
    }

    const collegeId = req.college._id;
    const departments = await Employee.distinct('department', { collegeId });
    
    res.status(200).json({
      message: 'Departments fetched successfully',
      data: departments || []
    });
  } catch (error) {
    console.error('Get Departments Error:', error);
    res.status(500).json({ message: 'Error fetching departments', error: error.message });
  }
};
